<?php

namespace app\user\model;

use think\Model;

class User extends Model
{
    //查询数据的返回类型
    protected $resultSetType = 'collection';

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //echo __FUNCTION__;
    }

    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //echo __FUNCTION__;
    }

    //获取器
    public function getNameAttr($value){
        return $value.'获取器修改';
    }
    //修改器-数据由修改器处理完成后再写入数据库
    public function setNameAttr($value){
        return '修改器处理'.$value;
    }
}
