<?php
return array (
  4 => 
  array (
    'id' => '4',
    'catid' => '18',
    'typeid' => '0',
    'title' => '公司大事件',
    'style' => '',
    'thumb' => '',
    'keywords' => '事件 公司',
    'description' => '公司大事件',
    'posids' => '0',
    'url' => 'http://www.phpcmslesson.io/index.php?m=content&c=index&a=show&catid=18&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1505272754',
    'updatetime' => '1505272782',
    'hitsid' => 'c-1-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '18',
    'typeid' => '0',
    'title' => '公司新闻2',
    'style' => '',
    'thumb' => '',
    'keywords' => '公司 新闻',
    'description' => '公司新闻2',
    'posids' => '0',
    'url' => 'http://www.phpcmslesson.io/index.php?m=content&c=index&a=show&catid=18&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1505355884',
    'updatetime' => '1505355905',
    'hitsid' => 'c-1-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>