<?php

namespace app\user\model;

use think\Model;
use traits\model\SoftDelete;

class User extends Model
{
    //查询数据的返回类型
    protected $resultSetType = 'collection';

    protected $autoWriteTimestamp = 'datetime';

    protected $readonly = ['email'];

    use SoftDelete;
    protected $deleteTime='delete_time';

    protected $insert = ['ip','status'];

    protected function setIpAttr()
    {
        return '192.168.1.1';
    }

    protected function setStatusAttr(){
        return '3';
    }

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //echo __FUNCTION__;
    }

    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //echo __FUNCTION__;

        //User::event('before_insert','bInsert');
        //事件快捷注册
//        User::beforeInsert(function ($user){
//            echo 'beforeInsert';
//        });
//
//        User::afterInsert(function ($user){
//           echo 'afterInsert';
//        });
    }

    public function bInsert($user){
        echo 'bInsert';
    }

   public function  getStatusTextAttr(){
        return '状态';
   }

    //获取器
    public function getNameAttr($value){
        return $value.'获取器修改';
    }
    //修改器-数据由修改器处理完成后再写入数据库
    public function setNameAttr($value){
        return '修改器处理'.$value;
    }

    //设置一对一关联
    public function profile()
    {
        return $this->hasOne('Profile');
    }
    //设置一对多关联
    public function comments(){
        return $this->hasMany('Comment');
    }

    //设置-多对多关联
    public function roles(){
        return $this->belongsToMany('Role','Rel');
    }
}
